@startuml
skinparam backgroundColor #F9F9F9
skinparam BoxBackgroundColor #FFFFFF
skinparam BoxBorderColor #2B7A78
skinparam BoxFontColor #2B7A78
skinparam ParticipantBorderColor #3A506B
skinparam ParticipantFontColor #3A506B
skinparam ArrowColor #1C2541
skinparam DatabaseColor #5BC0BE
skinparam ActorFontColor #FF1654
skinparam ActorBorderColor #FF1654

actor "Пользователь" as User
box "Backend" #ADD8E6
    participant "Backend" as Backend
    participant "Elasticsearch" as Elasticsearch
    database "Хранилище данных фильмов" as DataStore
end box

box "ML система" #98FB98
    participant "Эмбеддер (E5)" as Embedder
    database "Векторная БД (Milvus)" as Milvus
    participant "Reranker" as Reranker
end box

User -> Backend: 1) Поисковый запрос
Backend -> Elasticsearch: 2) Поисковый запрос
Elasticsearch ->  Backend: 3) Результат запроса
Backend -> DataStore: 4) Извлечение кандидатов на основе текста
Elasticsearch --> Backend: 5) Список кандидатов
Backend -> Embedder: 6) Эмбеддирование запроса
Embedder -> Backend: 7) Векторные эмбеддинги
Backend -> Milvus: 😍 Поиск похожих документов по векторным эмбеддингам
Milvus -> Backend: 9) Результаты по векторным эмбеддингам
Backend -> Reranker: 10) Уникальные кандидаты из Elasticsearch и Milvus
Reranker -> Backend: 11) Итоговое ранжирование
Backend -> User: 12) Отдача результатов пользователю

@enduml
