services:
  setup:
    image: docker.io/elasticsearch:8.14.3
    volumes:
      - setup_data:/usr/share/setup/data
    user: "0"
    command: >
      bash -c '
        echo "Waiting for Elasticsearch availability";
        until curl -s http://elasticsearch:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
        echo "Setting kibana_system password";
        until curl -s -X POST -u "elastic:password123" -H "Content-Type: application/json" http://elasticsearch:9200/_security/user/kibana_system/_password -d "{\"password\":\"password123\"}" | grep -q "^{}"; do sleep 10; done;
        echo "All done!";
      '
    networks:
      - shared

  elasticsearch:
    depends_on:
      - setup
    image: docker.io/elasticsearch:8.14.3
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - test_data:/usr/share/elasticsearch/data/
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=password123
      - bootstrap.memory_lock=true
    networks:
      - shared

  logstash:
    image: docker.io/logstash:8.14.3
    container_name: logstash
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
      - ls_data:/usr/share/logstash/data
    environment:
      - ELASTIC_PASSWORD=password123
    networks:
      - shared
    depends_on:
      - elasticsearch

  kibana:
    image: docker.io/kibana:8.14.3
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
      - kb_data:/usr/share/kibana/data
    environment:
      - ELASTICSEARCH_PASSWORD=password123
      - KIBANA_PASSWORD=password123
    networks:
      - shared
    depends_on:
      - elasticsearch

networks:
  shared:
    driver: bridge

volumes:
  setup_data:
  test_data:
  ls_data:
  kb_data: